# TODO: fix sensor positions. All are wrong, not in range for vrx base_link
wamv_gps:
    - name: gps_joint
      x: -0.9
      y: 0
      z: 1.8
      R: 0
      P: 0
      Y: 3.14159265358977
wamv_imu:
    - name: ahrs8_joint
      x: -0.9
      y: 0
      z: 1.8
      R: 0
      P: 0
      Y: 0

wamv_camera:
  - name: left_cam_joint
    x: 0.8
    y: 0
    z: 1.8
    R: 0
    P: 0
    Y: 1.3521
      
  - name: center_cam_joint
    x: 0.8
    y: 0
    z: 1.8
    R: 0
    P: 0
    Y: 0

  - name: right_cam_joint
    x: 0.8
    y: 0
    z: 1.8
    R: 0
    P: 0
    Y: -1.35208029820141

lidar:
    - name: puck_joint
      type: 32_beam
      x: -0.9
      y: 0
      z: 2.3
      R: 0
      P: 0
      Y: 0
    - name: puck_joint_front
      type: 32_beam
      x: 0.9
      y: 0
      z: 1.3
      R: 0
      P: 0
      Y: 0

wamv_p3d:
    - name: p3d_wamv
